# Main Configuration for Detect-Track System

# Video Input Configuration
video:
  # Source options: 'camera', 'file'
  source: 'camera'
  
  # Camera settings (when source is 'camera')
  camera:
    device_id: 0
    width: 640
    height: 480
    fps: 30
  
  # File settings (when source is 'file')
  file:
    path: ''  # Set this to your video file path
    start_frame: 0
    end_frame: -1  # -1 means until end of video

# Detection Configuration
detection:
  # Model options: 'yolov5n', 'yolov5s', 'yolov7', 'yolov8n', 'yolov8s'
  model: 'yolov8n'
  
  # Detection parameters
  confidence_threshold: 0.8
  iou_threshold: 0.7
  max_detections: 100
  
  # Model-specific settings
  yolov5:
    weights: 'yolov5n.pt'  # or 'yolov5s.pt'
  yolov7:
    weights: 'yolov7.pt'
  yolov8:
    weights: 'yolov8n.pt'  # or 'yolov8s.pt'

# Tracking Configuration
tracking:
  # Tracker options: 'nvdcf', 'deepsort', 'botsort'
  # Note: DeepSORT has compatibility issues with current NumPy versions
  # Recommended: Use 'botsort' (best performance) or 'nvdcf' (good fallbacks)
  algorithm: 'botsort'  # Default: Best performance and reliability
  
  # Common tracking parameters - IMPROVED FOR ROBUSTNESS
  max_lost_frames: 60    # Increased from 30 - keep tracks longer without detections
  min_track_length: 5    # Increased from 3 - require more frames before confirming track
  
  # DeepSORT specific settings
  deepsort:
    max_age: 60          # Increased from 30
    n_init: 5            # Increased from 3 - more frames to confirm track
    max_iou_distance: 0.8  # Increased from 0.7 - more lenient IoU matching
    max_cosine_distance: 0.3  # Increased from 0.2 - more lenient appearance matching
    
  # NvDCF specific settings (OpenCV tracker) - PERFORMANCE OPTIMIZED
  nvdcf:
    max_age: 60          # Increased from 30
    max_tracks: 4        # Conservative limit to prevent track fragmentation
    update_frequency: 3  # Update trackers every 3 frames for better performance
    
  # BOTSort specific settings - OPTIMIZED FOR TRACK PERSISTENCE
  botsort:
    track_high_thresh: 0.5   # Lowered from 0.6 - accept more detections
    track_low_thresh: 0.2    # Increased from 0.1 - filter very weak detections
    new_track_thresh: 0.8    # Increased from 0.7 - require higher confidence for new tracks
    match_thresh: 0.3        # Lowered from 0.8 - much more lenient matching (IoU > 0.3)
    motion_weight: 0.3       # NEW: reduce motion prediction influence
    iou_weight: 0.7          # NEW: emphasize IoU over motion

# Logging Configuration
logging:
  # Log levels: DEBUG, INFO, WARNING, ERROR
  level: 'INFO'
  
  # Output settings
  save_video: true
  save_detections: true
  save_tracks: true
  
  # Output paths
  output_dir: 'outputs'
  video_output: 'tracked_video.mp4'
  detections_output: 'detections.json'
  tracks_output: 'tracks.json'

# Performance Configuration
performance:
  # Frame processing
  skip_frames: 0  # Process every Nth frame (0 = process all)
  resize_input: true  # Resize camera input for performance (video files preserve original resolution)
  target_size: [640, 640]  # [width, height] - only applied to camera sources
  
  # Device settings
  device: 'auto'  # 'auto', 'cpu', 'cuda'
  
# Display Configuration
display:
  show_video: true
  show_detections: false
  show_tracks: true
  show_fps: true
  line_thickness: 2
  font_scale: 0.6 